---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: backend-auth
        image: bacon21/auth:latest
        ports:
          - containerPort: 3001
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: SECRET
                key: SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: MONGODB_URI
                key: MONGODB_URI
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: CLOUD_NAME
                key: CLOUD_NAME
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: CLOUD_API_KEY
                key: CLOUD_API_KEY
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: CLOUD_API_SECRET
                key: CLOUD_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: backend-auth
  ports:
    - port: 3001
      targetPort: 3001
