---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: backend-auth
        image: bacon21/auth:latest
        ports:
        - containerPort: 3001
        env:
        # Database Configuration
        - name: MONGODB_URI_AUTH
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_AUTH
        - name: DB_HOST
          value: "mongo-service"
        - name: DB_PORT
          value: "27017"
        
        # Application Secrets
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET
        
        # Cloudinary Configuration
        - name: cloud_name
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_name
        - name: cloud_api_key
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_api_key
        - name: cloud_api_secret
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_api_secret
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: backend-auth
  ports:
    - port: 3001
      targetPort: 3001
