---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: backend-auth
        image: bacon21/auth:latest
        ports:
        - containerPort: 3001
        env:
          - name: DB_HOST
            value: "mongodb-service" 
          - name: DB_PORT
            value: "27017"
          - name: db-cred
            valueFrom:
              secretKeyRef:
                name: db-cred
                key: MONGODB_URI_AUTH
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: backend-auth
  ports:
    - port: 3001
      targetPort: 3001
