---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: backend-auth
        image: bacon21/auth:latest
        ports:
          - containerPort: 3001
        env:
         SECRET: ${{ secrets.SECRET }}
         MONGODB_URI: ${{ secrets.MONGODB_URI }}
         CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
         CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
         CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: backend-auth
  ports:
    - port: 3001
      targetPort: 3001
