---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-discounts
  template:
    metadata:
      labels:
        app: backend-discounts
    spec:
      containers:
      - name: backend-discounts
        image: bacon21/discounts:latest
        ports:
        - containerPort: 3002
        env:
        # Database Configuration
        - name: MONGODB_URI_DISCOUNTS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_DISCOUNTS
        - name: DB_HOST
          value: "mongo-service"
        - name: DB_PORT
          value: "27017"
        
        # Application Secrets
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET
        
---
apiVersion: v1
kind: Service
metadata:
  name: discounts-service
spec:
  selector:
    app: backend-discounts
  ports:
    - port: 3002
      targetPort: 3002
