---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-discounts
  template:
    metadata:
      labels:
        app: backend-discounts
    spec:
      containers:
      - name: backend-discounts
        image: bacon21/discounts:latest
        ports:
          - containerPort: 3002
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: discounts-secrets
                key: SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: discounts-secrets
                key: MONGODB_URI
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: discounts-secrets
                key: CLOUD_NAME
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: discounts-secrets
                key: CLOUD_API_KEY
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: discounts-secrets
                key: CLOUD_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: discounts-service
spec:
  selector:
    app: backend-discounts
  ports:
    - port: 3002
      targetPort: 3002
