---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-items
  template:
    metadata:
      labels:
        app: backend-items
    spec:
      containers:
      - name: backend-items
        image: bacon21/items:latest
        ports:
        - containerPort: 3003
        env:
        # Database Configuration
        - name: MONGODB_URI_ITEMS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_ITEMS
        - name: DB_HOST
          value: "mongo-service"
        - name: DB_PORT
          value: "27017"
        
        # Application Secrets
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET
        
        # Cloudinary Configuration
        - name: cloud_name
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_name
        - name: cloud_api_key
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_api_key
        - name: cloud_api_secret
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: cloud_api_secret

         
---
apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  selector:
    app: backend-items
  ports:
    - port: 3003
      targetPort: 3003
