---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-items
  template:
    metadata:
      labels:
        app: backend-items
    spec:
      containers:
      - name: backend-items
        image: bacon21/items:latest
        ports:
          - containerPort: 3003
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: SECRET
                key: SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: MONGODB_URI
                key: MONGODB_URI
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: CLOUD_NAME
                key: CLOUD_NAME
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: CLOUD_API_KEY
                key: CLOUD_API_KEY
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: CLOUD_API_SECRET
                key: CLOUD_API_SECRET
         
---
apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  selector:
    app: backend-items
  ports:
    - port: 3003
      targetPort: 3003
