jobs:
  restart-and-cleanup:
    name: Restart Deployments & Clean Completed Pods
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }} \
            --overwrite-existing

      - name: Delete Completed Pods
        run: |
          echo "Cleaning up completed pods..."
          completed_pods=$(kubectl get pods --field-selector=status.phase=Succeeded -o name)
          if [ -n "$completed_pods" ]; then
            echo "$completed_pods" | xargs kubectl delete
          else
            echo "No completed pods found."
          fi

      - name: Rollout Restart Deployments
        run: |
          deployments=(
            "auth-deployment"
            "discounts-deployment"
            "items-deployment"
            "client-deployment"
          )

          for deployment in "${deployments[@]}"; do
            echo "Restarting $deployment..."
            kubectl rollout restart deployment/$deployment

            echo "Waiting for rollout to complete..."
            if ! kubectl rollout status deployment/$deployment --timeout=90s; then
              echo "::warning:: Rollout for $deployment timed out. Cleaning up failed pods."
              kubectl delete pods -l app=${deployment%-deployment} --field-selector=status.phase!=Running --force --grace-period=0 --validate=false
            fi
          done
